### ISSUE TITLE
Events registered from menu windows are executed multiple times

### ISSUE THREAD

**Issue by NSSure** [lospec/pixel-editor#101]
Any windows that are open from the main menu of the editor and register events when open are having those events registered multiple times.

1. Go to "File"
2. Click on "Save project"
3. Dismiss the window
4. Click on "Save project" again
5. Click "Save" in the window
6. The project file be saved twice.

This happens to "Save project", "Export", etc.

Need to add a key to track the registered events or create a method for removing registered events.

**Comment by unsettledgames** [comment]
Fixed in #87
