### ISSUE TITLE
BUG: in advanced mode it's possible to remove all colours from the palette

### ISSUE THREAD

**Issue by unsettledgames** [lospec/pixel-editor#110]
To reproduce:
- Open the editor in advanced mode
- Open the advanced palette dialogue (click on already selected colour or right click on a palette colour)
- Hold right mouse button to select all the colours in the palette
- Hit "Remove colours"
- Exit the dialogue

**Comment by amritrai5757** [comment]
I have solved this issue and making a pull request for this.
