### ISSUE TITLE
Stalled app while uploading a palette?

### ISSUE THREAD

**Issue by jywarren** [lospec/pixel-editor#15]
not sure if it's just me or what, but I tried uploading a slightly large PNG as a palette, and the site is not loading for me now. I'm so sorry if I caused that! I just didn't totally understand the load palette function. 

Thank you for lospec, i love it!

![muk-px](https://user-images.githubusercontent.com/24359/89482339-a949a280-d767-11ea-9369-45e6e8231f4e.png)

**Comment by unsettledgames** [comment]
Hi! Unfortunately, I'm not able to recreate the bug (I'm using the image you posted). By the way, if the app crashes, it should only crash for you (as it's client-side only) and you should be able to start the app again by visiting https://lospec.com/pixel-editor/app .
Did you take a screenshot of the console or saved the logs? If the error happens again, please, press F12, on the top menu of the window that appears click on "Console", right click wherever you want on the console window and then "Save as". You can then send us the log and we'll be able to investigate more 👍 

Is there anything weird you noticed before the app crashed?

**Comment by jywarren** [comment]
Oh that's so weird, I had guessed that it's client side but after this
happened I was unable to load the webpage at all! That's also why I didn't
get a log, bc the whole tab froze. But, so strange that even opening it in
another tab wouldn't load. Is there any persistent local storage that could
have been causing this if too big an image were saved somehow?

Thank you!

**Comment by jywarren** [comment]
Strange - ok, so on further investigation, I wonder if it has to do with the service worker -- does this app have offline capability? 

The strange thing is that i /still/ can't load https://lospec.com/pixel-editor/app; it just hangs. On inspection, the initial page gets a 200 success, but the reason I thought it was a service worker is that there's a second request that seems to hang, preventing the page from loading. I don't see any error messages. 

Here's the sequence, in a GIF:

![lospec](https://user-images.githubusercontent.com/24359/89668215-68f33d00-d8ab-11ea-85fa-266851cfac90.gif)

One correction, actually the image I used was this:

![crab](https://user-images.githubusercontent.com/24359/89668245-74466880-d8ab-11ea-90fd-d4e36b1cda66.png)

In incognito mode, it loads fine. 

Here's the network pane:

![image](https://user-images.githubusercontent.com/24359/89668640-1b2b0480-d8ac-11ea-9d17-30c16a9ebc56.png)

It seems like https://lospec.com/service-worker.js is not loading, perhaps? 

Hmm, any idea what is happening? I can't seem to clear the cache for this site. I'll try through the overall Chrome sites cache interface.

**Comment by unsettledgames** [comment]
Thank you for your investigation, this is going to be helpful. As a contributor, I don't have access to the server side of Lospec, so I'll let the main dev know about this issue so that it can be solved :)

**Comment by jywarren** [comment]
oh, thank you so much!
