### ISSUE TITLE
FEATURE: More selection tools

### ISSUE THREAD

**Issue by JamesTDG** [lospec/pixel-editor#36]
Implement new ways to select a section of a sprite, such as a lasso tool and a magic wand tool.

**Comment by unsettledgames** [comment]
Leaving the link of the Piskel repo, which has a lasso tool and magic wand implementation, might be useful to study its code: https://github.com/piskelapp/piskel/tree/master/src/js

**Comment by unsettledgames** [comment]
https://codepen.io/cranes/pen/GvobwB

**Comment by unsettledgames** [comment]
Magic wand and lasso tool coming soon @JamesTDG !
