### ISSUE TITLE
Hex color #000000 exports as transparent, not black

### ISSUE THREAD

**Issue by sloopygoop** [lospec/pixel-editor#47]
I've been using the Pixel Editor to change the palette of Game Boy Camera photos I take. Sometime in the last several months, any black in the image (#000000) becomes transparent when exporting as a .png, meaning I have to change any blacks to slightly off-black. I feel I didn't used to have to do that..

**Comment by unsettledgames** [comment]
Thanks for reporting the bug! We'll have a look into that as soon as possible.

**Comment by unsettledgames** [comment]
Apparently, the bug has been fixed by fixing other bugs in the latest pull request (#38) . The update should be online soon, but let us know if the problem persists after the next release :)
