### ISSUE TITLE
Request: ability to create filename/destination when exporting

### ISSUE THREAD

**Issue by sloopygoop** [lospec/pixel-editor#48]
When exporting a pixel image in Chrome/Windows, the image instantly goes to my Downloads folder with its own templated "pixel-dimensions date etc." filename. It would be wonderful if I could choose the directory I was saving the image to, and to give it a custom filename as well.

**Comment by unsettledgames** [comment]
Thanks for the request! We'll try to implement that in the release after the next one :)

**Comment by unsettledgames** [comment]
Regarding this one, a dialogue window entirely dedicated to export / save options would be very useful, especially in anticipation of implementing more file formats.

**Comment by unsettledgames** [comment]
With #58 you can now choose a custom filename. If you want to choose the location of your file, you'll have to set your browser to do so :)
