### ISSUE TITLE
  Аxis locking for selection and shapes

### ISSUE THREAD

**Issue by DanilBatr** [lospec/pixel-editor#72]
Single, static reference layer: the user can draw over it (could take the place of the checkerboard when used)
Multiple reference images
The user can drag them around the canvas
The user can resize them to a certain extent
When placed on the canvas, the reference image is exactly below the current layer, so that the user can always see the image and draw over it

Axis locking for rect and line tool (lock line tool to 30, 45, 60 degrees)
Let the user use the rect and the rect selection to draw or select squares
Let the user lock an axis when moving a selection, so that it only moves vertically or horizontally

OS: Windows 10
Browser: Chrome, Edge
Thanks in advance

**Comment by unsettledgames** [comment]
Hello! Do you want to work on all of these? If so I suggest starting from a single reference layer. I made a few changes to how selections work so I'd like to avoid conflicts
