### ISSUE TITLE
Switching a color to black makes the color not work 

### ISSUE THREAD

**Issue by skeddles** [lospec/pixel-editor#8]
upon turning a color to black in the pixel art editor, it shows as black, but will draw like it is the background color. switching the color does not fix it.

originally opened by Landon Britt on [https://bitbucket.org/skeddles/lospec/issues/33/switching-a-color-to-black-makes-the-color](https://bitbucket.org/skeddles/lospec/issues/33/switching-a-color-to-black-makes-the-color)

**Comment by unsettledgames** [comment]
This one has been fixed and should probably be closed.
