### ISSUE TITLE
Please may Lospec Pixel Editor be liberated? 

### ISSUE THREAD

**Issue by throwaway1037** [lospec/pixel-editor#83]
**Describe the bug**
This is a freedom issue: Losepc Pixel Editor is propritary software, and as such I ask that it be liberated by being released under a [libre license](https://gnu.org/licenses/license-list.html), so it will respect the freedom and community of its users.

**To Reproduce**
1. Go to the README file.
2. Observe the propritary license.

**Expected behavior**
A license file with a libre license.
Ideally a clear license notice would be placed at the top of each file, as is best practise.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: any
 - Browser: any
 - Version: latest

**Smartphone (please complete the following information):**
 - Device: any
 - OS: any
 - Browser: any
 - Version: any

**Additional context**
For more information about libre software, visit the [Free Software Foundation](https://fsf.org) website and the [GNU](https://gnu.org) website.

Thank you.

**Comment by unsettledgames** [comment]
Liberation completed

**Comment by throwaway1037** [comment]
Thank you.
Does the license also apply to all previous versions before the license was added?
