### ISSUE TITLE
Add Dockerfile (and maybe pipelines for tests?)

### ISSUE THREAD

**Issue by blueprismo** [lospec/pixel-editor#93]
**Is your feature request related to a problem? Please describe.**
No, I just love Docker :) :whale: 

**Describe the solution you'd like**
Dependencies are minimal in this project, but why not having it dockerized and that way it will always work everywhere [with the same cpu-arch]? (and there will be no mismatches between versions (npm, node, OS running it...)).

I can contribute with a Dockerfile and some initial github actions workflow.

**Additional context**
None :100:

**Comment by unsettledgames** [comment]
Implemented in #99
