### ISSUE TITLE
invalid license

### ISSUE THREAD

**Issue by hacknorris-aka-penguin** [lospec/pixel-editor#94]
in readme its mentioned to not redistribute, while license file says otherwise (i know most of gpl licenses, and it just tells you to share code of copies, doesnt lock for not sharing, its otherwise...)

**Comment by unsettledgames** [comment]
Thanks for notifying, we forgot to update the Readme after adding the license. I see you made a fork so feel free to fix that, otherwise we can fix it too :)

**Comment by hacknorris-aka-penguin** [comment]
> Thanks for notifying, we forgot to update the Readme after adding the license. I see you made a fork so feel free to fix that, otherwise we can fix it too :)

ok

**Comment by unsettledgames** [comment]
Fixed by #95
